//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWWBewertungPortal.Models.Datenbank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Benutzer
    {
        public Tab_Benutzer()
        {
            this.Tab_Bewertung = new HashSet<Tab_Bewertung>();
            this.Tab_Kommentar = new HashSet<Tab_Kommentar>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public string Nickname { get; set; }
        public string Email { get; set; }
        public string Passwort { get; set; }
        public string Geschlecht { get; set; }
        public string AvartarID { get; set; }
    
        public virtual ICollection<Tab_Bewertung> Tab_Bewertung { get; set; }
        public virtual ICollection<Tab_Kommentar> Tab_Kommentar { get; set; }
    }
}
