//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWWBewertungPortal.Models.Datenbank
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WWWBewertungsModellContainer : DbContext
    {
        public WWWBewertungsModellContainer()
            : base("name=WWWBewertungsModellContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tab_Benutzer> Tab_BenutzerSet { get; set; }
        public DbSet<Tab_Lokation> Tab_LokationSet { get; set; }
        public DbSet<Tab_Lokation_Photo> Tab_Lokation_PhotoSet { get; set; }
        public DbSet<Tab_Kommentar> Tab_KommentarSet { get; set; }
        public DbSet<Tab_Bewertung> Tab_BewertungSet { get; set; }
    }
}
